GSA/devsecops-example

- terraform/assume_role_policy.json
- terraform/flow_log.tf
- terraform/role_policy.json
- terraform/vpc.tf
Also added flow logs, for troubleshooting.
> fix DNS resolution from the instance(s)

- terraform/rds.tf
...as recommended, and easier to get set up.
> switch from postgres to mysql

- terraform/vpc.tf
This should fix `sudo`, per
https://forums.aws.amazon.com/message.jspa?messageID=495274
> enable DNS hostnames

- README.md
- terraform/dns.tf
- terraform/outputs.tf
- terraform/vars.tf
> use DNS for referencing the database

- README.md
> expand on the Important Concepts section

- terraform/ec2.tf
- terraform/outputs.tf
- terraform/rds.tf
- terraform/security.tf
> fix integration with devsecops-infrastructure

- README.md
https://github.com/GSA/DevSecOps-Infrastructure/pull/10 reminded me of this.
> add Convention Over Configuration as an Important Concept

- .circleci/config.yml
- README.md
- terraform/network.tf
/cc https://github.com/GSA/DevSecOps-Infrastructure/pull/12
> validate Terraform using CircleCI

- README.md
Moving this to [the Design Considerations doc](https://docs.google.com/document/d/1xpQUSBDP8not-AbChf_vM2grdGzDE83IJYx9i9W00Qc/edit#heading=h.b6ztauie5ret), which is a more centralized place we are already putting this type of information.
> remove Important Concepts section

- terraform/network.tf
Temporary fix to make the repository work again.
> lock to old version of VPC module

- README.md
- ansible/requirements.yml
- ansible/wordpress.yml
- packer.json
Closes #11 & https://trello.com/c/YVG1wBXB/125-harden-instance-in-devsecops-example.
> harden the WordPress instance

- .circleci/config.yml
- README.md
- terraform/bootstrap/main.tf
- terraform/bootstrap/variables.tf
More consistent to create resources using Terraform rather than through the AWS CLI.
> create a Terraform module for bootstrapping

- ansible/group_vars/jenkins/main.yml
https://github.com/geerlingguy/ansible-role-jenkins#role-variables
> always upgrade Jenkins to the latest version

- README.md
> add workaround for circular dependency when creating the environment for the first time

- terraform/env/network.tf
- terraform/mgmt/network.tf
Forced version 1.11.0 to fix an additional subnet issue
> Terraform vpc version

- .circleci/config.yml
- README.md
- terraform/env/variables.tf
- terraform/mgmt/terraform.tfvars.example
- terraform/mgmt/variables.tf
- terraform/modules/alerting/main.tf
- terraform/modules/alerting/variables.tf
Fixes the build, by providing an example variables file that's copied in. Also did some cleanup of other variables.
> specify the general_availability_endpoint for mgmt

- packer/jenkins.json
> Rhel cloudwatch fix

- README.md
- ansible/group_vars/all/main.yml
- ansible/install_python.yml
- ansible/jenkins.yml
- ansible/requirements.yml
- ansible/wordpress.yml
- packer/jenkins.json
- packer/wordpress.json
Depends on https://github.com/GSA/security-benchmarks/pull/18.
> extract code for creating base AMIs

- .circleci/config.yml
> use working_directory instead of cd

- .circleci/config.yml
- README.md
> small miscellaneous cleanup

- Dockerfile
- README.md
...which I only recently learned existed. Convenient!
https://docs.docker.com/engine/userguide/eng-image/multistage-build/
> use multi-stage build for Dockerfile

- .circleci/config.yml
Also streamlined the validation.
> split the AMI build from the environment deploy

- .circleci/config.yml
- terraform/env/aws.tf
- terraform/mgmt/aws.tf
This shows what would change.
https://www.terraform.io/guides/running-terraform-in-automation.html#testing-pull-requests-with-terraform-plan
> run 'terraform plan' for the env on all builds

- terraform/env/network.tf
- terraform/env/variables.tf
- terraform/mgmt/network.tf
- terraform/mgmt/variables.tf
Just a refactor, which also caused my editor to automatically reformat the Terraform code. Therefore, easier to understand the diff ignoring whitespace.
> use CIDR function for computing ranges

- .circleci/config.yml
- ansible/egress_proxy.yml
- ansible/requirements.yml
- packer/egress_proxy.json
- terraform/env/proxy.tf
- terraform/env/rds.tf
- terraform/env/variables.tf
> Add Egress Proxy

- ansible/egress_proxy.yml
- ansible/wordpress.yml
Fix indention error in ansible playbook (Closes #83)
> Fix pre_tasks syntax (Closes #83)
